### 逻辑运算

In [2]:
import numpy as np

In [3]:
stock_change = np.random.normal(loc=0, scale=1, size=(8, 10))

In [4]:
stock_change

array([[-0.15300127,  0.70389633,  0.69301884, -0.35333398,  0.32463125,
         1.58457126, -0.22211039, -0.20524564,  1.04071951, -0.32022153],
       [-0.11259722,  0.68780473, -0.12602656, -1.77213498, -1.47953757,
        -0.13869312, -0.99001123, -1.92643681,  0.67201353, -0.37154792],
       [-0.57970734,  0.52036877,  0.05771015, -1.05702836,  3.02075626,
        -0.01720521,  1.67692736, -0.93173482, -0.23598452, -1.54540283],
       [ 0.65564039,  0.34991612, -0.02679558, -1.31992426,  0.95960559,
        -0.01323778,  0.60085575,  1.59890778, -0.86652588,  2.1373348 ],
       [ 0.99418836,  0.08581109,  1.12703444, -1.17488511,  0.28382814,
        -0.72595193,  0.29201744, -1.40951649,  2.88471718,  0.16652846],
       [-1.27300928, -0.40661829, -1.12781498, -0.61512274,  0.76036834,
         2.24496715, -0.70693072,  1.29690691, -1.40341721,  0.06968774],
       [ 0.41524942, -0.76006381, -0.55250802,  0.41011491, -0.6353757 ,
         1.49641379, -0.59148493,  1.13811587

In [5]:
# 逻辑判断：如果涨跌幅大于0.5就标记为True，否则为false
stock_change>0.5

array([[False,  True,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False, False, False, False, False,  True,
        False],
       [False,  True, False, False,  True, False,  True, False, False,
        False],
       [ True, False, False, False,  True, False,  True,  True, False,
         True],
       [ True, False,  True, False, False, False, False, False,  True,
        False],
       [False, False, False, False,  True,  True, False,  True, False,
        False],
       [False, False, False, False, False,  True, False,  True, False,
        False],
       [ True,  True,  True, False,  True, False,  True, False,  True,
        False]])

In [6]:
# bool索引
stock_change[stock_change>0.5]=1.1

In [7]:
stock_change

array([[-0.15300127,  1.1       ,  1.1       , -0.35333398,  0.32463125,
         1.1       , -0.22211039, -0.20524564,  1.1       , -0.32022153],
       [-0.11259722,  1.1       , -0.12602656, -1.77213498, -1.47953757,
        -0.13869312, -0.99001123, -1.92643681,  1.1       , -0.37154792],
       [-0.57970734,  1.1       ,  0.05771015, -1.05702836,  1.1       ,
        -0.01720521,  1.1       , -0.93173482, -0.23598452, -1.54540283],
       [ 1.1       ,  0.34991612, -0.02679558, -1.31992426,  1.1       ,
        -0.01323778,  1.1       ,  1.1       , -0.86652588,  1.1       ],
       [ 1.1       ,  0.08581109,  1.1       , -1.17488511,  0.28382814,
        -0.72595193,  0.29201744, -1.40951649,  1.1       ,  0.16652846],
       [-1.27300928, -0.40661829, -1.12781498, -0.61512274,  1.1       ,
         1.1       , -0.70693072,  1.1       , -1.40341721,  0.06968774],
       [ 0.41524942, -0.76006381, -0.55250802,  0.41011491, -0.6353757 ,
         1.1       , -0.59148493,  1.1       

In [8]:
#  通用判断函数
# np.all()：只要有一个false就返回false ,全都为TRUE才返回TRUE
np.all(stock_change>0.5)

False

In [9]:
# np.any():只要有一个为true就返回TRUE，全都为false返回false
np.any(stock_change>0.5)

True

In [11]:
# 判断stock_change[0:2,0:5]是否全部上涨
stock_change[0:2,0:5]>0

array([[False,  True,  True, False,  True],
       [False,  True, False, False, False]])

In [12]:
np.all(stock_change[0:2,0:5]>0)

False

In [13]:
np.any(stock_change[0:2,0:5]>0)

True

In [14]:
# 三元运算符 np.where()
# # 判断前四个股票前四天的涨跌幅 大于0的置为1，否则为0
temp=stock_change[:4,:4]

In [15]:
temp

array([[-0.15300127,  1.1       ,  1.1       , -0.35333398],
       [-0.11259722,  1.1       , -0.12602656, -1.77213498],
       [-0.57970734,  1.1       ,  0.05771015, -1.05702836],
       [ 1.1       ,  0.34991612, -0.02679558, -1.31992426]])

In [16]:
np.where(temp>0,1,0)

array([[0, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 1, 0, 0]])

In [17]:
temp>0

array([[False,  True,  True, False],
       [False,  True, False, False],
       [False,  True,  True, False],
       [ True,  True, False, False]])

In [18]:
# 判断前四个股票前四天的涨跌幅 大于0.5并且小于1的，换为1，否则为0
# 判断前四个股票前四天的涨跌幅 大于0.5或者小于-0.5的，换为1，否则为0
np.logical_and(temp>0.5,temp<1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [19]:
np.logical_or(temp>0.5,temp<-0.5)

array([[False,  True,  True, False],
       [False,  True, False,  True],
       [ True,  True, False,  True],
       [ True, False, False,  True]])

### 统计运算

In [20]:
# 统计指标 min max mean 

In [21]:
# 需求：股票涨跌幅统计运算
temp

array([[-0.15300127,  1.1       ,  1.1       , -0.35333398],
       [-0.11259722,  1.1       , -0.12602656, -1.77213498],
       [-0.57970734,  1.1       ,  0.05771015, -1.05702836],
       [ 1.1       ,  0.34991612, -0.02679558, -1.31992426]])

In [24]:
np.max(temp,axis=1)

array([1.1, 1.1, 1.1, 1.1])

In [23]:
temp.max()

1.1

In [25]:
np.argmax(temp,axis=1)

array([1, 1, 1, 0])

### 数组间运算

In [26]:
# 数组与数的运算
arr = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])

In [27]:
# 每个元素除10
arr / 10

array([[0.1, 0.2, 0.3, 0.2, 0.1, 0.4],
       [0.5, 0.6, 0.1, 0.2, 0.3, 0.1]])

In [28]:
# 数组 与数组的运算
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])


In [30]:
# 广播机制 broadcast 为了是的两个不同形状的ndarray进行数学运算
# 当操作两个数组额时候，numpy会逐个比对他们的shape，只有在下列情况下，两个数组才能进行运算：
# 1）维度相等
# 2） shape（其中相对应的一个地方为1）

In [31]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [32]:
arr1 # (2,6)
arr2 # (2,1)
# 第一列两个维度都为2，第二列有一个1，可以进行运算

array([[1],
       [3]])

In [33]:
arr1 * arr2

array([[ 1,  2,  3,  2,  1,  4],
       [15, 18,  3,  6,  9,  3]])

### 矩阵运算

In [34]:
# ndarray存储矩阵
data = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [35]:
data

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [36]:
# matrix存储矩阵
data_mat=np.mat([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [37]:
data_mat

matrix([[80, 86],
        [82, 80],
        [85, 78],
        [90, 90],
        [86, 82],
        [82, 90],
        [78, 80],
        [92, 94]])

In [38]:
# 矩阵乘法
# 形状要求：(m,n)*(n*l)=(m,l)

In [39]:
weights=np.array([[0.3],[0.7]])

In [43]:
# 如果使用的是ndarray存储的：np.matmul   np.dot
np.matmul(data,weights)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [44]:
np.dot(data,weights)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [47]:
weights_mat=np.mat([[0.3],[0.7]])

In [48]:
# 如果是matrix存储的
data_mat * weights_mat

matrix([[84.2],
        [80.6],
        [80.1],
        [90. ],
        [83.2],
        [87.6],
        [79.4],
        [93.4]])

In [46]:
# ndarray也可以使用@计算
data @ weights

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [49]:
# data   和  weight不能进行计算，因为不满足广播机制

In [50]:
# 合并，分割

In [51]:
a = stock_change[:2, 0:4]
b = stock_change[4:6, 0:4]

In [52]:
a

array([[-0.15300127,  1.1       ,  1.1       , -0.35333398],
       [-0.11259722,  1.1       , -0.12602656, -1.77213498]])

In [53]:
b

array([[ 1.1       ,  0.08581109,  1.1       , -1.17488511],
       [-1.27300928, -0.40661829, -1.12781498, -0.61512274]])

In [54]:
np.hstack((a,b))

array([[-0.15300127,  1.1       ,  1.1       , -0.35333398,  1.1       ,
         0.08581109,  1.1       , -1.17488511],
       [-0.11259722,  1.1       , -0.12602656, -1.77213498, -1.27300928,
        -0.40661829, -1.12781498, -0.61512274]])

In [56]:
np.concatenate((a,b),axis=1)

array([[-0.15300127,  1.1       ,  1.1       , -0.35333398,  1.1       ,
         0.08581109,  1.1       , -1.17488511],
       [-0.11259722,  1.1       , -0.12602656, -1.77213498, -1.27300928,
        -0.40661829, -1.12781498, -0.61512274]])

In [57]:
np.concatenate((a,b),axis=0)

array([[-0.15300127,  1.1       ,  1.1       , -0.35333398],
       [-0.11259722,  1.1       , -0.12602656, -1.77213498],
       [ 1.1       ,  0.08581109,  1.1       , -1.17488511],
       [-1.27300928, -0.40661829, -1.12781498, -0.61512274]])

### IO操作与数据输出

In [61]:
# 读取数据
data=np.genfromtxt("test.csv",delimiter=",")

In [62]:
data

array([[  nan,   nan,   nan,   nan],
       [  1. , 123. ,   1.4,  23. ],
       [  2. , 110. ,   nan,  18. ],
       [  3. ,   nan,   2.1,  19. ]])

In [63]:
# numpy遇到字符串会解析成nan，因此一般不使用numpy读取数据

In [64]:
# 如何处理遇到缺失值nan的问题
# 两种方法：1.直接丢弃样本；2.使用替换/插补法

In [65]:
def fill_nan_by_column_mean(t):
    for i in range(t.shape[1]):
        # 计算nan的个数
        nan_num = np.count_nonzero(t[:, i][t[:, i] != t[:, i]])
        if nan_num > 0:
            now_col = t[:, i]
            # 求和
            now_col_not_nan = now_col[np.isnan(now_col) == False].sum()
            # 和/个数
            now_col_mean = now_col_not_nan / (t.shape[0] - nan_num)
            # 赋值给now_col
            now_col[np.isnan(now_col)] = now_col_mean
            # 赋值给t，即更新t的当前列
            t[:, i] = now_col
    return t

In [66]:
fill_nan_by_column_mean(data)

array([[  2.  , 116.5 ,   1.75,  20.  ],
       [  1.  , 123.  ,   1.4 ,  23.  ],
       [  2.  , 110.  ,   1.75,  18.  ],
       [  3.  , 116.5 ,   2.1 ,  19.  ]])